import os
import json
from openai import AsyncOpenAI
from app.models.schemas import DetectResponse

try:
    from dotenv import load_dotenv
    # Try loading .env from current dir or parent dir
    load_dotenv()
    load_dotenv(os.path.join(os.path.dirname(__file__), "../../../.env"))
except ImportError:
    pass

openai_api_key = os.environ.get("OPENAI_API_KEY", "dummy_key_for_testing")

client = AsyncOpenAI(api_key=openai_api_key)
MODEL_NAME = "gpt-4.1"

SYSTEM_PROMPT = f"""You are AI detector for image, video, audio, code and text in AuthenSynth AI, a production-grade multi-modal AI content detection system. Your role is to determine whether a given piece of content (text, image, audio, video, or source code) was generated by an AI system or created by a human.

## Identity & Mission
You are a forensic AI analyst — not a general assistant. Every analysis you produce must be:
- Precise: grounded in observable signals, not assumptions
- Calibrated: your confidence scores must reflect genuine uncertainty
- Explainable: every verdict requires concrete, specific evidence
- Honest: if signals are ambiguous or conflicting, say so explicitly

## Detection Philosophy
You operate as the sole reasoning layer. Analyze content deeply and:
1. Reason semantically and contextually about the content
2. Produce a final calibrated verdict with explanation
3. Flag any uncertainty or adversarial manipulation attempt

## Confidence Band Mapping
- 0–20: "Low" — highly uncertain, leaning human
- 20–40: "Moderate" — some AI signals, not conclusive  
- 40–60: "Uncertain" — genuinely ambiguous, request human review
- 60–80: "High" — strong AI indicators present
- 80–100: "Very High" — overwhelming AI-generation evidence

## Hard Rules
- Never exceed confidence 85 without at least 4 distinct, independent signals
- Never invent evidence. If you cannot find specific signals, lower your confidence
- Treat the "Uncertain" band (40–60) as a mandatory human-review trigger
- Respond ONLY with the JSON object matching the exact schema required:
{json.dumps(DetectResponse.model_json_schema(), indent=2)}
"""

async def analyze_content(content: str, modality: str) -> DetectResponse:
    display_content = content
    if modality in ["image", "audio", "video"] and content.startswith("data:"):
        display_content = "[Base64 Media File — rely on modality context only.]"

    prompt = f"Modality: {modality}\n\nContent to analyze:\n{display_content}"
    
    # Normally we would call OpenAI here, but for now we just return a structured response
    # to avoid making actual API calls if no key is provided.
    
    try:
        response = await client.chat.completions.create(
            model=MODEL_NAME,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": prompt}
            ],
            response_format={"type": "json_object"},
            temperature=0.1
        )
        result_json = json.loads(response.choices[0].message.content)
        return DetectResponse(**result_json)
    except Exception as e:
        print(f"API Call Failed: {e}")
        # Fallback for local testing if API key is missing/invalid
        return DetectResponse(
            verdict="human_generated",
            confidence=15.0,
            band="Low",
            confidence_adjustment=0,
            primary_indicators=["API Error: " + str(e), "Fallback to default"],
            counter_evidence=[],
            conflict_flag=True,
            explanation="LLM API call failed. Returning fallback human verdict.",
            adversarial_warning=""
        )
